title: lib C++ Operation Log
theme: jekyll-theme-leap-day
description: >
  A small C++ library for logging debug messages (like function entry and
  exit, dumping variables, or 3D visualizations of models).
baseurl: /cpp-operation-log
url: https://pavpen.github.io/cpp-operation-log/
github_username: pavpen

# Build settings
markdown: kramdown
permalink: /:year/:title:output_ext
